### ISSUE TITLE
400 Error (Axios) - while sending contract function call to relayer 

### ISSUE THREAD

**Issue by divine-comedian** [OpenZeppelin/defender-sdk#252]
defender-sdk version: 1.9.0
OS: Linux 22.04 LTS
Typescript

I am trying to run a function call to my relayer on Sepolia - the Relayer is setup, has some gas, the API keys and secret I know are correct. When I run my function it returns with a bad request error. I am unable to debug from this error if there is an issue with my code or if there is an issue with defender-sdk. The error does not give me sufficient information to debug. 

## Here is the code I am trying to run to my relayer: 

```
export interface Credentials {
    apiKey: string;
    secretKey: string;
}

export async function sendNFT(credentials: Credentials, recipient: string, tokenId: number) {
    const nftContractAddress = process.env.NFT_CONTRACT_ADDRESS as string;
    console.log('this is the nft contract address', nftContractAddress);
    console.log('these are the credentials inside the function',credentials);
    const client = new Defender({relayerApiKey: credentials.apiKey, relayerApiSecret: credentials.secretKey});
    const hexedTokenId = numberToHex(tokenId)
    const data = encodeFunctionData({
        abi: miBarrioABI,
        functionName: 'safeMint',
        args: [recipient, 1],
    });
    console.log('this is the data', data);
    let txRes: any;
    try {
        txRes = await client.relaySigner.sendTransaction({
         to: nftContractAddress,
         value: 0,
         speed: 'fast',
         gasLimit: '21000',
         data: data
       });
       console.log(txRes);
    } catch (err) {
        console.log(err);
    }
  
    console.log(txRes);
    return txRes.hash;
  }

sendNFT(credentials, "0xAC4cda272DEF2019e36CB227D506b5969aA3b248", 1);

```
## Here is the contract function safeMint() for reference: 

```
function safeMint(address to, uint256 tokenId) public onlyRole(MINTER_ROLE) {
        _safeMint(to, tokenId);
    }
```

## Here is the error from the terminal output

```
DefenderApiResponseError: Request failed with status code 400
    at rejectWithDefenderApiError (/home/mitch/github/vote-bot/node_modules/@openzeppelin/defender-sdk-base-client/lib/api/api.js:10:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Axios.request (/home/mitch/github/vote-bot/node_modules/axios/dist/node/axios.cjs:3872:14)
    at async /home/mitch/github/vote-bot/node_modules/@openzeppelin/defender-sdk-relay-signer-client/lib/api/index.js:33:21
    at async RelaySignerClient.apiCall (/home/mitch/github/vote-bot/node_modules/@openzeppelin/defender-sdk-base-client/lib/api/client.js:44:20) {
  request: { path: '/txs', method: 'POST' },
  response: {
    status: 400,
    statusText: 'Bad Request',
    data: {
      message: 'Internal Error: An error has occurred while processing the request'
    }
``` 

While there could be issue in my code or my approach, the error as you can see doesn't give me much to understand how to proceed.

**Comment by mutharibayub** [comment]
I'm also facing this issue. I created a local project to deploy and upgrade one of my contracts through defender v2. The project has not changed at all but it has stopped working and started giving this error (both on deployment and upgrading).

**Comment by emnul** [comment]
Hi @divine-comedian could you please open a support request by emailing defender-support@openzeppelin.com so we can gather additional information regarding your account which will help us identify the issue here.

**Comment by divine-comedian** [comment]
Making a really complicated way for your users to report issues is a sure fire way to make sure nothing gets fixed!

**Comment by shahnami** [comment]
> Making a really complicated way for your users to report issues is a sure fire way to make sure nothing gets fixed!

Hi @divine-comedian, could you try run the script again, if the issue persists, it should at least return a more verbose error message this time. Apologies for the inconvenience.

**Comment by shahnami** [comment]
This was a known issue and has been fixed 2 months ago. Closing due to inactivity.
